config:
  aws:region: us-east-1
  microsservico-node-infra:ordersDatabaseUrl:
    secure: AAABAH1pDj2dA5xdR/W7579+oxeN+8TNw2lpCsN4VebXCk5apTnInocge9wHZ62Ji2S51KiIPifa/0pqOO8Um9FtQVaP++YCDH0kwNZihHt+xUfGfeFceaWJJRC5hOgDUEzH19lHZRv3abUdYuhgrxt0J5WdehEm+/JFzF+/V2zijqDtlS4ZpKNdyzGXFJ/tq+/YkQh3J10Wq+qBeYIe+1eiTVW2YyZWiixmSlc=
  microsservico-node-infra:otlpHeaders:
    secure: AAABAMC2l6zHmqDtDE+1+DSEWkxxbuE1JjMaUscQI0j/yR50GTqWkB3kieFU+hc57nUA7x0E2A5jhcS9lO8fqyJXmxsxWJpIIcz5+Wm0ukdZw3DukxO03f0WUgoJ/rwnAZH91oyhfa1y1XAqj45pMIS3m7XBxPQSQKw9iU5ygdXo4Yf38IBaTeZF7+EtieM+lxF7AXSn5SeG9Y+yh9lI8DWjSi0/h8eGmV1qSbJpLCKy7ezg1AtYB4tjweKF1SrJaWWjZ5V0J1LMRGP3PowVpw13EQqNYk1mOaCmGZNfrRRCHXkP48G4wK4vxH2TvskmM7icqGmp
  microsservico-node-infra:invoicesDatabaseUrl:
    secure: AAABANQ34CW4Ppqzxae6jtaGrZCKxohJtvVpawzVsmOmpvCPKPrbnaLwCzDkWVQCGEHYNFDIzxWhfyiZrqNLF5zyHeOGb4F4mpI3jjcFRBfd+nsIenMIA57czKVFnBktZx/5Q8iyBqfEXB2GOfgTTNqR/pRSYYS0fq/WjH9PsUNVEnzuqQNyYoacoxYS4/E++BFrGHZwzf6TciLNWFJUFFfsotsUOg32XljUnE0SilAM
  microsservico-node-infra:otlpEndpoint: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp
  microsservico-node-infra:brokerUsername:
    secure: AAABADSjfqQhLfcwf4F7AzJvIdlw8VGqcWccg9gFfl3Ai9rK
  microsservico-node-infra:brokerPassword:
    secure: AAABADKQGzp4WclqNnCCAYx3TXJWfcHJ7lO5Sv/mGhLN5SBw
  microsservico-node-infra:paymentsDatabaseUrl:
    secure: AAABAHWVxWPiv6Azf5dvQqhcfZpaHB+qISq560pL0ndzbu0WSVS9Amvg2MqDI9yLNaqGjyenPVfTkzQXkT+azsvZzyokcIEV8Z05HfYk0HEWmL8jTKLBy82dWYNquB8U4b2k5l/4cLMnUbbcWOmZs9yOKSj/cxhvfMYQgvxeTKahFe20nq6Xx031O5Mu54xu8Kec+S9YXOMtlTXVD5UbVpCkp7xAkFr68SqUCbDQglGDj/JXrg==
