_format_version: "3.0"
_transform: true

services:
  - name: app-orders
    # url: http://host.docker.internal:3333 DEV
    url: ${ORDERS_SERVICE_URL}
    routes:
      - name: api-orders
        protocols:
          - http
          - https
        paths:
          - /orders
          - /customers
        strip_path: false

  - name: app-invoices
    # url: http://host.docker.internal:3334
    url: ${INVOICES_SERVICE_URL}
    routes:
      - name: api-invoices
        protocols:
          - http
          - https
        paths:
          - /invoices
        strip_path: false

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Content-Type
        - Authorization
