name: app-invoices

services:
  invoices-pg:
    image: postgres:16
    ports:
      - "5483:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=invoices
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - invoices_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  invoices_pg_data:
